// Code generated by mockery v2.20.0. DO NOT EDIT.

package mocks

import (
	context "context"
	entity "excel-receiver/entity"

	mock "github.com/stretchr/testify/mock"
)

// QueueInterface is an autogenerated mock type for the QueueInterface type
type QueueInterface struct {
	mock.Mock
}

// ProduceQueue provides a mock function with given fields: ctx, requestData
func (_m *QueueInterface) ProduceQueue(ctx context.Context, requestData *entity.Queue) error {
	ret := _m.Called(ctx, requestData)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *entity.Queue) error); ok {
		r0 = rf(ctx, requestData)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

type mockConstructorTestingTNewQueueInterface interface {
	mock.TestingT
	Cleanup(func())
}

// NewQueueInterface creates a new instance of QueueInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewQueueInterface(t mockConstructorTestingTNewQueueInterface) *QueueInterface {
	mock := &QueueInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
